apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yed3lp7xm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yed3lp7xm-python 
  name: yed3lp7xm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yed3lp7xm-python 
